# noinspection YAMLSchemaValidation
name: ${name}
version: '${version}'
main: team.idealstate.minecraft.next.spigot.ExampleMinecraftNext
load: STARTUP
authors:
- ideal-state
depend:
- minecraft-next
commands:
  exampleminecraftnext:
    aliases:
    - emn
