oneByte: 1
oneShort: 2
oneInt: 123
oneLong: 123456
oneFloat: 1.23
oneDouble: 1.23
oneBoolean: true
oneChar: 'a'
oneString: "abc"
oneEnum: FIRST
oneArray:
- 1
- 2
- 3
oneList:
- 1
- 2
- 3
- 4
- 5
- 6
oneSet:
- only one
- only one
- only one
- only one
- only one
- only one
oneMap:
  a: 1
  b: "2"
  c:
    c1: '3'